name: roberta-base
model:
  model_name: roberta-base
  tokenizer_name: roberta-base
  max_length: 512
  device: cuda
  train:
    batch_size: 16 
    lr: 1e-3
    epochs: 10 
    warmup_steps: 0
    weight_decay: 0.0001
    max_grad_norm: 1.0
